"use client";

import { useRouter } from "next/navigation";
import Link from "next/link";
import { api } from "@/trpc/react";
import { Button } from "@/components/ui/button";
import { toast } from "sonner";
import { ArrowRight } from "lucide-react";
import { SessionForm, SessionFormData } from "@/components/admin/session-form";

export default function NewSessionPage() {
  const router = useRouter();

  const createMutation = api.session.create.useMutation({
    onSuccess: (session) => {
      toast.success("تم إنشاء الجلسة بنجاح");
      router.push(`/admin/sessions/${session.id}`);
    },
    onError: (error) => {
      toast.error(error.message || "حدث خطأ أثناء إنشاء الجلسة");
    },
  });

  const handleSubmit = async (formData: SessionFormData) => {
    const dateTime = new Date(`${formData.date}T${formData.time}`);

    await createMutation.mutateAsync({
      // sessionNumber is auto-generated by backend
      title: formData.title,
      description: formData.description || undefined,
      date: dateTime,
      location: formData.location || undefined,
      guestName: formData.guestName || undefined,
      guestProfile: formData.guestProfile || undefined,
      maxParticipants: parseInt(formData.maxParticipants),
      maxCompanions: parseInt(formData.maxCompanions),
      requiresApproval: formData.requiresApproval,
      showParticipantCount: formData.showParticipantCount,
      showCountdown: formData.showCountdown,
      showGuestProfile: formData.showGuestProfile,
      inviteOnly: formData.inviteOnly,
      inviteMessage: formData.inviteMessage || undefined,
      sendQrInEmail: formData.sendQrInEmail,
      slug: formData.slug || undefined,
      registrationDeadline: formData.registrationDeadline
        ? new Date(formData.registrationDeadline)
        : undefined,
      customConfirmationMessage: formData.customConfirmationMessage || undefined,
    });
  };

  return (
    <div className="space-y-6">
      {/* Header */}
      <div className="flex items-center gap-4">
        <Button variant="ghost" size="icon" asChild>
          <Link href="/admin/sessions">
            <ArrowRight className="h-4 w-4" />
          </Link>
        </Button>
        <div>
          <h1 className="text-2xl font-bold">جلسة جديدة</h1>
          <p className="text-muted-foreground">
            إنشاء جلسة جديدة لثلوثية الأعمال
          </p>
        </div>
      </div>

      <SessionForm
        mode="create"
        onSubmit={handleSubmit}
        isPending={createMutation.isPending}
        onCancel={() => router.push("/admin/sessions")}
      />
    </div>
  );
}
