"use client";

import { useRouter, useSearchParams } from "next/navigation";
import Link from "next/link";
import { api } from "@/trpc/react";
import { Button } from "@/components/ui/button";
import { Skeleton } from "@/components/ui/skeleton";
import { toast } from "sonner";
import { ArrowRight, Loader2 } from "lucide-react";
import { SessionForm, SessionFormData } from "@/components/admin/session-form";
import { parseFormDateToUTC } from "@/lib/timezone";

export default function NewSessionPage() {
  const router = useRouter();
  const searchParams = useSearchParams();
  const duplicateFromId = searchParams.get("duplicateFrom");

  // Fetch source session if duplicating
  const { data: sourceSession, isLoading: isLoadingSource } = api.session.getAdminDetails.useQuery(
    { id: duplicateFromId! },
    { enabled: !!duplicateFromId }
  );

  // Build initial data from source session
  const initialData: Partial<SessionFormData> | undefined = sourceSession
    ? {
        title: `نسخة من ${sourceSession.title}`,
        description: sourceSession.description || "",
        // Leave date/time empty so user must set new values
        date: "",
        time: "",
        location: sourceSession.location || "",
        locationUrl: sourceSession.locationUrl || "",
        guestIds: sourceSession.sessionGuests?.map((sg: { guestId: string }) => sg.guestId) || [],
        maxParticipants: String(sourceSession.maxParticipants),
        maxCompanions: String(sourceSession.maxCompanions),
        requiresApproval: sourceSession.requiresApproval,
        showParticipantCount: sourceSession.showParticipantCount,
        showCountdown: sourceSession.showCountdown,
        showGuestProfile: sourceSession.showGuestProfile,
        inviteOnly: sourceSession.inviteOnly,
        inviteMessage: sourceSession.inviteMessage || "",
        sendQrInEmail: sourceSession.sendQrInEmail,
        showSocialMediaFields: sourceSession.showSocialMediaFields,
        showRegistrationPurpose: sourceSession.showRegistrationPurpose,
        showCateringInterest: sourceSession.showCateringInterest,
        customConfirmationMessage: sourceSession.customConfirmationMessage || "",
        // Don't copy slug - will be auto-generated
        slug: "",
        // Don't copy registration deadline
        registrationDeadline: "",
        // Valet service - copy from source
        valetEnabled: sourceSession.valetEnabled ?? false,
        valetLotCapacity: String(sourceSession.valetLotCapacity ?? 0),
        valetRetrievalNotice: String(sourceSession.valetRetrievalNotice ?? 5),
      }
    : undefined;

  const createMutation = api.session.create.useMutation({
    onSuccess: (session) => {
      toast.success("تم إنشاء الحدث بنجاح");
      router.push(`/admin/sessions/${session.id}`);
    },
    onError: (error) => {
      toast.error(error.message || "حدث خطأ أثناء إنشاء الحدث");
    },
  });

  const handleSubmit = async (formData: SessionFormData) => {
    // Convert Saudi time input to UTC for database storage
    const dateTime = parseFormDateToUTC(formData.date, formData.time);

    await createMutation.mutateAsync({
      // sessionNumber is auto-generated by backend
      title: formData.title,
      description: formData.description || undefined,
      date: dateTime,
      location: formData.location || undefined,
      guestIds: formData.guestIds || [],
      maxParticipants: parseInt(formData.maxParticipants),
      maxCompanions: parseInt(formData.maxCompanions),
      requiresApproval: formData.requiresApproval,
      showParticipantCount: formData.showParticipantCount,
      showCountdown: formData.showCountdown,
      showGuestProfile: formData.showGuestProfile,
      inviteOnly: formData.inviteOnly,
      inviteMessage: formData.inviteMessage || undefined,
      sendQrInEmail: formData.sendQrInEmail,
      showSocialMediaFields: formData.showSocialMediaFields,
      showRegistrationPurpose: formData.showRegistrationPurpose,
      showCateringInterest: formData.showCateringInterest,
      // slug field is commented out in form - removed from mutation
      // Convert registration deadline from Saudi time to UTC
      registrationDeadline: formData.registrationDeadline
        ? parseFormDateToUTC(formData.registrationDeadline.split("T")[0], formData.registrationDeadline.split("T")[1])
        : undefined,
      // customConfirmationMessage field is commented out in form - removed from mutation
      locationUrl: formData.locationUrl || undefined,
      // Valet service
      valetEnabled: formData.valetEnabled,
      valetLotCapacity: parseInt(formData.valetLotCapacity) || 0,
      valetRetrievalNotice: parseInt(formData.valetRetrievalNotice) || 5,
    });
  };

  // Show loading state while fetching source session for duplication
  if (duplicateFromId && isLoadingSource) {
    return (
      <div className="space-y-6">
        <div className="flex items-center gap-4">
          <Skeleton className="h-10 w-10" />
          <div className="space-y-2">
            <Skeleton className="h-8 w-48" />
            <Skeleton className="h-4 w-64" />
          </div>
        </div>
        <div className="flex items-center justify-center py-12">
          <Loader2 className="h-8 w-8 animate-spin text-muted-foreground" />
        </div>
      </div>
    );
  }

  return (
    <div className="space-y-6">
      {/* Header */}
      <div className="flex items-center gap-4">
        <Button variant="ghost" size="icon" asChild>
          <Link href="/admin/sessions">
            <ArrowRight className="h-4 w-4" />
          </Link>
        </Button>
        <div>
          <h1 className="text-2xl font-bold">
            {duplicateFromId ? "نسخ الحدث" : "حدث جديد"}
          </h1>
          <p className="text-muted-foreground">
            {duplicateFromId
              ? "إنشاء حدث جديد بناءً على حدث سابق"
              : "إنشاء حدث جديد لثلوثية الأعمال"}
          </p>
        </div>
      </div>

      <SessionForm
        mode="create"
        initialData={initialData}
        onSubmit={handleSubmit}
        isPending={createMutation.isPending}
        onCancel={() => router.push("/admin/sessions")}
      />
    </div>
  );
}
